## ABHISHEK KUMAR
## 20BAI10384

## LOGISTIC REGRESSION

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('Scores.csv')

In [5]:
df

experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [8]:
df.experience = df.experience.fillna(0)

In [10]:
df.test_score = df.test_score.fillna(0)

In [11]:
df

experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         0.0                7   72000
7        11.0         7.0                8   80000

In [13]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [14]:
reg.intercept_

24823.523106605797

In [15]:
reg.coef_

array([3077.8642085 ,  999.7856246 , 2118.48834717])

In [18]:
reg.predict([[25,10,10]])

/home/prince/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([132952.86803663])

In [19]:
reg.predict([[0,10,10]])

/home/prince/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([56006.26282424])

In [20]:
reg.predict([[0,0,0]])

/home/prince/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([24823.52310661])